name: My workfow

# Déclenchement automatique à chaque push sur la branche "main"
on:
  push:
    branches: [ "master" ]
    workflow_dispatch: {}
    schedule: 
      - cron: '0 0 * * *'

jobs:
  run-tests:
    runs-on: windows-latest  # ou windows-latest, macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test  # ou npx cypress run, jest, etc.


      # 1) Upload videos as an artifact
      - name: Upload Cypress Videos
      uses: actions/upload-artifact@v3
      with:
        name: cypress-videos
        path: cypress/videos

    # 2) Upload screenshots as an artifact
    - name: Upload Cypress Screenshots
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: cypress/screenshots