name: My workflow

# Déclenchement automatique à chaque push sur la branche "main"
on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}
  schedule: 
      - cron: '0 23 * * *'  # Executes at midnight Tunis Time (UTC+1)

jobs:
  run-tests:
    runs-on: windows-latest  # ou windows-latest, macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx cypress run  # ou npx cypress run, jest, etc.
        env:
          CYPRESS_VIDEO: 1  # Capture video of the test run
          CYPRESS_SCREENSHOTS: 1  # Capture screenshots on failure


      # 1) Upload videos as an artifact
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: warn

      # 2) Upload screenshots as an artifact
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn

     