name: My workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}
  schedule: 
    - cron: '0 22 * * *'  # Executes at midnight Tunis Time (UTC+1)

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Cypress tests
      - name: Run Cypress Tests
        run: npx cypress run --browser electron --record || true
        env:
          # Ensure Cypress generates video
          CYPRESS_VIDEO: true
          CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true

      # Debug: Check where Cypress saves videos
      - name: List Cypress Video Files
        run:  |
          echo "Checking if videos and screenshots directories exist..."
          dir cypress\videos
          dir cypress\screenshots

      # Upload Cypress Videos
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4
          if-no-files-found: warn

      # Upload Cypress Screenshots
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*.png
          if-no-files-found: warn
